[package]
name = "devel"
version = "0.1.0"
edition = "2021"

[dependencies]
async-process = "2.2.3"
iced = "0.12.1"
open = "5.1.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["rt-multi-thread", "macros"] }
